### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 0x15d3** [HeliosClient/HeliosClient#5]
### What happened?

i keep getting this error while starting

`---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-02-03 00:32:58
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'heliosclient'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/moandjiezana/toml/TomlWriter$Builder
	at dev.heliosclient.managers.ConfigManager.<init>(ConfigManager.java:22)
	at dev.heliosclient.system.Config.<init>(Config.java:42)
	at dev.heliosclient.HeliosClient.<clinit>(HeliosClient.java:39)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.moandjiezana.toml.TomlWriter$Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 15 more`

### How do you replicate this bug?

i did tried using other clients and tried with only heliosclient none of them worked i keep getting errored but when i start Minecraft Client at intellij it do works

### Version

Latest developer build

### What operating system are you using?

Windows

### Check before sumitting

- [X] This bug isn't cause by incompatibility with other mods (I'm able to reproduce this without any other mod installed). Doesn't apply for incompatibility with mods that this client is expected to be working with eg. sodium, mod menu. 
- [X] I'm sure that this bug wasn't already reported.

- [X] I'm sure that this bug wasn't already patched (I'm able to reproduce this on the latest build).

**Comment by ElBe-Plaq** [comment]
I can reproduce the issue.

**Comment by ElBe-Plaq** [comment]
It seems to be something about the Toml writer dependency not being installed.

**Comment by tanishisherewithhh** [comment]
You need to download the client with the sources (i.e dependency prebuilt with the client).

**Comment by tanishisherewithhh** [comment]
Check this action output file:

https://github.com/HeliosClient/HeliosClient/actions/runs/7772610303

**Comment by 0x15d3** [comment]
> It seems to be something about the Toml writer dependency not being installed.

it is installed actually

> Check this action output file:
> 
> https://github.com/HeliosClient/HeliosClient/actions/runs/7772610303
> 
> Use this instead: https://github.com/HeliosClient/HeliosClient/actions/runs/7772836911

and i dont want release im going to add modules

**Comment by 0x15d3** [comment]
i tried building from last commit and when i try to launch minecraft it got crashes again https://mclo.gs/9gIy7rH

**Comment by 0x15d3** [comment]
it did worked btw i just deleted the 
`        File defaultCapeFile = new File(CAPE_DIRECTORY, DEFAULT_CAPE);
        try (InputStream inputStream = CapeManager.class.getResourceAsStream("/assets/heliosclient/capes/" + DEFAULT_CAPE)) {
            assert inputStream != null;
            HeliosClient.LOGGER.info("Copying default cape in directory");
            Files.copy(inputStream, defaultCapeFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            HeliosClient.LOGGER.info("Copying completed");
        } catch (IOException e) {
            e.printStackTrace();
        }`
on loadCapes function

**Comment by 0x15d3** [comment]
```java
        try (InputStream inputStream = CapeManager.class.getResourceAsStream("/assets/heliosclient/capes/" + DEFAULT_CAPE)) {
            if (inputStream != null) {
                HeliosClient.LOGGER.info("Copying default cape to the directory");
                Files.copy(inputStream, defaultCapeFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                HeliosClient.LOGGER.info("Copying completed");
            } else {
                HeliosClient.LOGGER.error("Failed to load default cape resource");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
```
added this and still working

**Comment by tanishisherewithhh** [comment]
> and i dont want release im going to add modules
Its built by github actions, not release.




> ```java
>         try (InputStream inputStream = CapeManager.class.getResourceAsStream("/assets/heliosclient/capes/" + DEFAULT_CAPE)) {
>             if (inputStream != null) {
>                 HeliosClient.LOGGER.info("Copying default cape to the directory");
>                 Files.copy(inputStream, defaultCapeFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
>                 HeliosClient.LOGGER.info("Copying completed");
>             } else {
>                 HeliosClient.LOGGER.error("Failed to load default cape resource");
>             }
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
> ```
> 
> added this to CapeManager.java:42 and still working

Ahh I forgot to add exception handling for that case.

**Comment by 0x15d3** [comment]
idk why but it keeps failing to load capes

**Comment by tanishisherewithhh** [comment]
Fixed with latest commit

**Comment by 0x15d3** [comment]
> does it crash or just the error message is printed?
just the error message

**Comment by tanishisherewithhh** [comment]
I am getting the same problem but only with the builded jar version. Otherwise its able to work in intellij enviornment

**Comment by tanishisherewithhh** [comment]
It has been fixed from my side in the latest commit

**Comment by 0x15d3** [comment]
i already fixed it so i can close this comment thanks for helping
